# Generated by Django 4.2.29 on 2026-10-06 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0145_version_7_4_0"),
    ]

    operations = [
        migrations.AddField(
            model_name="tool",
            name="_hazard_footprint",
            field=models.ManyToManyField(
                blank=True,
                db_table="NEMO_tool_hazard_footprint",
                help_text="Areas that become unsafe while this tool is in use. Tool reservations are blocked when any of these areas (or their sub-areas) is reserved by someone else or has a scheduled outage.",
                related_name="hazard_footprint_tools",
                to="NEMO.area",
                verbose_name="hazard footprint",
            ),
        ),
    ]
