# Generated by Django 4.2.29 on 2026-10-06 19:47

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0145_version_7_4_0"),
    ]

    operations = [
        migrations.AddField(
            model_name="tool",
            name="_hazard_areas",
            field=mptt.fields.TreeManyToManyField(
                blank=True,
                db_table="NEMO_tool_hazard_areas",
                help_text="Areas this tool creates a safety hazard in. The tool cannot be reserved while any of these areas is reserved by another user or closed for a scheduled outage. Staff cannot override this.",
                related_name="hazard_for_tools",
                to="NEMO.area",
                verbose_name="hazard areas",
            ),
        ),
    ]
